# Generated by Django 4.2.2 on 2023-08-21 13:20

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('block', models.BooleanField(default=False)),
                ('color', colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=20, samples=None)),
                ('sequence_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=30)),
                ('block', models.BooleanField(default=False)),
                ('sequence_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('add_or_subtract_price', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('quantity', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcolormodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
            ],
        ),
    ]
