# Generated by Django 4.2.3 on 2023-10-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_delete_basketmodel'),
        ('product', '0005_alter_productmodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcommentmodel',
            name='by_user',
        ),
        migrations.RemoveField(
            model_name='productcommentmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimagemodel',
            name='by_user',
        ),
        migrations.RemoveField(
            model_name='productimagemodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productlikemodel',
            name='by_user',
        ),
        migrations.RemoveField(
            model_name='productlikemodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='by_user',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productratingmodel',
            name='by_user',
        ),
        migrations.RemoveField(
            model_name='productratingmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsizemodel',
            name='by_user',
        ),
        migrations.RemoveField(
            model_name='productsizemodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productsizemodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producttagmodel',
            name='by_user',
        ),
        migrations.RemoveField(
            model_name='producttagmodel',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductColorModel',
        ),
        migrations.DeleteModel(
            name='ProductCommentModel',
        ),
        migrations.DeleteModel(
            name='ProductImageModel',
        ),
        migrations.DeleteModel(
            name='ProductLikeModel',
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
        migrations.DeleteModel(
            name='ProductRatingModel',
        ),
        migrations.DeleteModel(
            name='ProductSizeModel',
        ),
        migrations.DeleteModel(
            name='ProductTagModel',
        ),
    ]
