# Generated by Django 4.2.3 on 2023-09-29 13:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='message',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
