# Generated by Django 4.2.3 on 2023-10-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdModel',
        ),
    ]
