# Generated by Django 4.2.3 on 2023-10-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_productcommentmodel_by_user_and_more'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
