# Generated by Django 4.2.2 on 2023-08-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcommentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommentmodel',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
