# Generated by Django 4.2.2 on 2023-08-16 19:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogcommentmodel_block_alter_blogmodel_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=100000),
        ),
    ]
