# Generated by Django 4.2.3 on 2023-10-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimagemodel',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='author',
        ),
        migrations.DeleteModel(
            name='BlogCommentModel',
        ),
        migrations.DeleteModel(
            name='BlogImageModel',
        ),
        migrations.DeleteModel(
            name='BlogModel',
        ),
    ]
