# Generated by Django 4.2.3 on 2023-10-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='postcode',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
