# Generated by Django 4.2.3 on 2023-10-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
        ('order', '0003_delete_ordermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('block', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('history', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('postcode', models.DecimalField(decimal_places=0, max_digits=7)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
