# Generated by Django 4.2.3 on 2023-10-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_basketmodel_remove_order_user_delete_basket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketmodel',
            name='ammount',
        ),
        migrations.RemoveField(
            model_name='basketmodel',
            name='total_count',
        ),
    ]
