# Generated by Django 4.2.3 on 2023-10-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_alter_basketmodel_color_alter_basketmodel_sizes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasketModel',
        ),
    ]
