# Generated by Django 4.2.3 on 2023-10-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket', '0006_initial'),
        ('users', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
        ('product', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketmodel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcolormodel'),
        ),
        migrations.AddField(
            model_name='basketmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel'),
        ),
        migrations.AddField(
            model_name='basketmodel',
            name='sizes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productsizemodel'),
        ),
        migrations.AddField(
            model_name='basketmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
    ]
